### ISSUE TITLE
[ ✏️ ] UI Refinements.

### ISSUE THREAD

**Issue by evanlinjin** [kittycash/wallet#117]
@bradkendall Great work on the UI so far! The following are refinements that will make the interface feel smoother in my opinion.

- [x] **Double the margins on the sides.**

  ![](https://media.discordapp.net/attachments/447712013406306314/448107211529519104/unknown.png?width=1474&height=1193)

- [x] **Spacing of "Breed", "Feed All", "0 items" elements shouldn't change on resize.**

  "Breed", "Feed All" and "0 items" should have consistent spacing between them, and anchored on the right side.

  ![](https://media.discordapp.net/attachments/447712013406306314/448107847272759297/Picture1.png)
  ![](https://media.discordapp.net/attachments/447712013406306314/448107850196320276/Picture2.png)

- [x] **Remove "KittyCash" text under logo, as we already have this in window title.**

  <img width="136" alt="image" src="https://user-images.githubusercontent.com/14065705/40486607-54f9068c-5f94-11e8-8182-f51d738bc208.png">

- [x] **No whitespace under wallet.**

  Content should expand all the way to the bottom of the window.

  <img width="1312" alt="image" src="https://user-images.githubusercontent.com/14065705/40486720-a20b9336-5f94-11e8-855f-9d83afdf2371.png">

- [x] **Top & bottom margins between content and frame should always be equal.**

  <img width="1312" alt="image" src="https://user-images.githubusercontent.com/14065705/40486792-e3c30282-5f94-11e8-8cf2-a10a09cd214e.png">

- [x] **Only content should be scrollable.**

  Toolbar shouldn't disappear like this.

  <img width="1312" alt="image" src="https://user-images.githubusercontent.com/14065705/40486960-51525ea6-5f95-11e8-9b41-b066afde834c.png">

- [x] **Pop-ups should have rounded corners, and "x" button should use icon.**

  <img width="755" alt="image" src="https://user-images.githubusercontent.com/14065705/40487044-8f230fbe-5f95-11e8-89f7-e3cfa00af199.png">

- [x] **Implement subtle shadows as shown in mockups.**

  <img width="620" alt="image" src="https://user-images.githubusercontent.com/14065705/40487148-d5068808-5f95-11e8-9cae-1f16b35f9531.png">

**Comment by jdknives** [comment]
@bradkendall any news for that? is it done?

**Comment by bradkendall** [comment]
Yes, this is all done.  Waiting to merge everything in before I close it.
