### ISSUE TITLE
[ 🐛 ] POST request as application/json redirecting to GET.

### ISSUE THREAD

**Issue by bradkendall** [kittycash/wallet#133]
**Describe the bug**
When sending a POST request through the wallet proxy with the `Content-Type:application/json` header, the request gets redirected as a GET request.  

Additionally, if we are going to be sending `application/json` requests through the proxy, the proxy will need to handle OPTIONS requests and return 2xx.

**To Reproduce**
Running:
```curl -d '{"kitty_id":"1", "to":"to_address", "sig":"signature"}' -H "Content-Type: application/json" -X POST -i http://127.0.0.1:6148/v1/transfer```

Responds with:

`
HTTP/1.1 301 Moved Permanently
Location: https://api.kittycash.com/v1/transfer?
Date: Tue, 12 Jun 2018 08:34:08 GMT
Content-Length: 0
`

**Expected behavior**
`HTTP/1.1 308 Permanent Redirect
Location: https://api.kittycash.com/v1/transfer
Date: Tue, 12 Jun 2018 08:34:08 GMT
Content-Length: 0`

See: https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/308

**Screenshots**
N/A

**Desktop (please complete the following information):**
macOS 10.13.5

**Additional context**
N/A

**Comment by evanlinjin** [comment]
@bradkendall The "poxy" only allows calls with specific paths through. Which endpoint is this?

**Comment by bradkendall** [comment]
`v1/transfer`

**Comment by jdknives** [comment]
@evanlinjin @bradkendall pretty sure I asked this a long time ago alr, but is this finished? or being worked on?

**Comment by bradkendall** [comment]
I believe it has been completed.  @evanlinjin ?

**Comment by 128-95** [comment]
@bradkendall what's the status of this one? #146 Seems to be waiting on a merge...

**Comment by bradkendall** [comment]
I have fixed it.  It will be closed when I merge out wallet code.
