### ISSUE TITLE
Review for PR #2

### ISSUE THREAD

**Issue by briancaine** [kittycash/wallet#3]
My (late) review for PR #2:

If anyone decides to act on any of these suggestions, we can open up separate issues for each task.

#### store

Questions:
* [The Images in MetaDB](https://github.com/kittycash/iko/blob/23597ee1642c27edcdc442dc410b1ce06f968814/legacy/ex24/store/db_meta.go#L30)... are those visual kitty images? like bitmaps or something?
* In regards to the kitty IDs, is there any chance an ID could become invalid? That is, we'll never have gaps in our set, right?
* I see the [kitty IDs](https://github.com/kittycash/iko/blob/23597ee1642c27edcdc442dc410b1ce06f968814/legacy/ex24/store/db_meta.go#L15), can we add an explicit type alias for the kitty ID type?
* in [kitty_ownership.go](https://github.com/kittycash/iko/blob/23597ee1642c27edcdc442dc410b1ce06f968814/legacy/ex24/store/kitty_ownership.go#L93), can't we just implement [a custom json.Marshaler](https://godoc.org/encoding/json#Marshaler) for this?
* Small grammar suggestion for store.go: [StoreOption should be OptionStorer](https://github.com/kittycash/iko/blob/23597ee1642c27edcdc442dc410b1ce06f968814/legacy/ex24/store/store.go#L7), the noun (another option is how you did it in state.go, StoreOptionAction works too). Some of the other functions in that file should be renamed to reflect that.

#### exchange

* what's the difference between a [KittyID and a KittyAddress](https://github.com/kittycash/iko/blob/23597ee1642c27edcdc442dc410b1ce06f968814/legacy/ex24/exchange/exchange.go#L10)?

#### scanner

No questions, but I do like how you use type aliases for ID types and enums and other things.

### kchain

Add a [kittyID type to state.go](https://github.com/kittycash/iko/blob/23597ee1642c27edcdc442dc410b1ce06f968814/src/kchain/state.go#L14) (and any other places where they get used)

Questions:

* why does [MemoryState.addresses](https://github.com/kittycash/iko/blob/23597ee1642c27edcdc442dc410b1ce06f968814/src/kchain/state.go#L36) have that type? Like, couldn't it just be map[address][]KittyID
* [chain.go:92](https://github.com/kittycash/iko/blob/23597ee1642c27edcdc442dc410b1ce06f968814/src/kchain/chain.go#L92) is this incomplete?
* transaction.go what's [a gen transaction](https://github.com/kittycash/iko/blob/23597ee1642c27edcdc442dc410b1ce06f968814/src/kchain/transaction.go#L25)? (I'm guessing a transfer transaction is moving a kitty from one owner to another? Is a gen transaction one where the kitty is first ~~made~~ born?)

### http

One question: where are we going to be deploying this API? is it for the wallet?

**Comment by evanlinjin** [comment]
> Add a kittyID type to state.go (and any other places where they get used)

Implemented.

> why does MemoryState.addresses have that type? Like, couldn't it just be map[address][]KittyID

Changed.

> chain.go:92 is this incomplete?

Completed.

> transaction.go what's a gen transaction? (I'm guessing a transfer transaction is moving a kitty from one owner to another? Is a gen transaction one where the kitty is first made born?)

Yes.

> One question: where are we going to be deploying this API? is it for the wallet?

ASAP. Yes, and for IKO "master" node that determines what goes on blockchain.

**Comment by 128-95** [comment]
> transaction.go what's a gen transaction? (I'm guessing a transfer transaction is moving a kitty from one owner to another? Is a gen transaction one where the kitty is first ~made~ born?)

You should add more comments to your code, @evanlinjin to prevent this questions.

**Comment by evanlinjin** [comment]
@128-95

> You should add more comments to your code, @evanlinjin to prevent this questions.

https://github.com/kittycash/wallet/blob/master/src/iko/transaction.go#L135
