### ISSUE TITLE
First build - iterative feedback

### ISSUE THREAD

**Issue by 128-95** [kittycash/wallet#63]
@bradkendall:
```
Kitty-API:
1. need search endpoint
2. need kitty & box images returned
3. I think order is backwards (Check order by kitty_id DESC)
4. Need legendary bool

Teller:
1. Need to get ready for integration

Marketplace: 
1. What have we decided for the coin type selection?  Do you like my idea of selecting the coin with the reserve button?  Any other ideas where to place it
2. QR codes - Do we need a prefix for the data?  Scan it and let me know if that is right.
3. The designs didn’t have direction for the sort order.  I just added another select box for that.  We may want to change it to an icon?

Wallet App:
1. What are the top bars supposed to do?  Refresh makes sense.  What is the hamburger for?  Are there going to be settings?  What goes in there?
2. What is the connected area supposed to indicate?
3. We need to make a decision on autoupdating or update checking.  If we are going to avoid downloading & auto installing binaries, electron-release-server may be overkill (It may not though because it can keep everything organized for us.  I think our two options are:
    1. Build an endpoint (probably in kitty-api?) with a current version variable.  I can then hit that every app launch and compare the version numbers.  If there is a new version, I will pop up an alert with a link to https://www.kittycash.com/
    2. Setup electron release server and instead of auto downloading new versions, simply pop up an alert with a link to https://www.kittycash.com/
4. Any word yet how the wallet app is coming or when it will be ready for integration?
5. I think we will want to set a minimum window size?  How small do you think we need to go.  The menu isn’t super responsive right now, but I think 400px minimum would be great.  It would put each row of kitties with 1 column.
6. We still need certificates to sign the apps.  I think it auto-signed the mac app with my apple developer certificate.  There are going to be all sorts of security errors opening these apps.```

**Comment by 128-95** [comment]
**Kitty-API:**
> 2. need kitty & box images returned

We can use the imgs in kitties/examples in Syncthing as demo? They have the dna string as name

**Marketplace:**
> 1. What have we decided for the coin type selection?  Do you like my idea of selecting the coin with the reserve button?  Any other ideas where to place it

Imo we should re-display the kitty/box details above the email field together with coin type selection

> QR codes - Do we need a prefix for the data?  Scan it and let me know if that is right.

Pure address in QR should be fine for now. Once we have a decent explorer we might want to add url to explorer to it, but even then I'm not sure if we should do that

> 3. The designs didn’t have direction for the sort order.  I just added another select box for that.  We may want to change it to an icon?

Yeah, an arrow should be better

**Wallet App:**
> 1. What are the top bars supposed to do?  Refresh makes sense.  What is the hamburger for?  Are there going to be settings?  What goes in there?

That hamburger should only be displayed in the wallet afaik and would hide/display the different wallets

> What is the connected area supposed to indicate?

CXO status of syncing? Accessibility to endpoints of teller etc?

> We need to make a decision on autoupdating or update checking.  If we are going to avoid downloading & auto installing binaries, electron-release-server may be overkill (It may not though because it can keep everything organized for us.  I think our two options are: [...]

I would go for update check. I don't really have a preference, whatever is the most structured/easy sounds good. Release server kind of sounds like for it to me

> Any word yet how the wallet app is coming or when it will be ready for integration?

We have to poll Samuel when everything is ready so he can complete the wallet

> 5. I think we will want to set a minimum window size?  How small do you think we need to go.  The menu isn’t super responsive right now, but I think 400px minimum would be great.  It would put each row of kitties with 1 column.

Good for me

> We still need certificates to sign the apps.  I think it auto-signed the mac app with my apple developer certificate.  There are going to be all sorts of security errors opening these apps.

@therealssj  what is Skycoin doing at the moment? Getting them signed and everything might be good since we aim for a non-tech/crypto public

**Comment by briancaine** [comment]
Have we turned this into tickets yet?

I know there's the kitty_id DESC/ASC issue, and the app signing issue. Do we want to make any other issues out of this?

**Comment by 128-95** [comment]
What still needs to be done:
- [ ] Search endpoints aka kitty explorer

Other than that I think it's all addressed, done or in progress.

**Comment by briancaine** [comment]
@128-95 is there a ticket for that? If not, can you create one and close this ticket?
