### ISSUE TITLE
Sign apps

### ISSUE THREAD

**Issue by 128-95** [kittycash/wallet#74]
Get certificate

**Comment by bradkendall** [comment]
@jdknives Here is what I found regarding code signing:

**Linux:**

Code signing doesn’t seem to be supported in Linux.  Can someone verify this?

**Windows:** 

Digicert seems to be the most recommended on electron forums: https://www.digicert.com/code-signing/

Certum seems to have a discounted product for open source projects: https://www.certum.eu/certum/cert,offer_en_open_source_cs.xml

To sign an app on Windows, there are two types of certificates:

EV Code Signing Certificate
Code Signing Certificate

Both certificates work with auto-update. The regular (and often cheaper) Code Signing Certificate shows a warning during installation that goes away once enough users installed your application and you've built up trust. The EV Certificate has more trust and thus works immediately without any warnings. However, it is not possible to export the EV Certificate as it is bound to a physical USB dongle. 

**Mac OS:** 

Mac OS Code signing requires an Apple Developer Program Account.  That can be applied for here: https://developer.apple.com/programs/enroll/

**Comment by 128-95** [comment]
@briancaine @bradkendall Any updates on this?

**Comment by evanlinjin** [comment]
Is this done?

**Comment by bradkendall** [comment]
We decided to put this on hold for now.
