### ISSUE TITLE
Connection endpoints

### ISSUE THREAD

**Issue by 128-95** [kittycash/wallet#77]

**Comment by briancaine** [comment]
What's this about? Could we get a more detailed description?

**Comment by bradkendall** [comment]
This is an endpoint to show the connection status to the network inside the wallet app: 

<img width="1280" alt="screen shot 2018-04-03 at 6 05 05 am" src="https://user-images.githubusercontent.com/416080/38230306-171ba2be-3705-11e8-8442-ec216b9f54e2.png">

**Comment by briancaine** [comment]
@bradkendall ok, thanks

@evanlinjin Could I get a time estimate for this?

How long would it take to:
* implement the feature itself
* write the tests

**Comment by evanlinjin** [comment]
- [ ] Implement endpoint: Thursday
- [ ] Write tests: Friday

**Comment by evanlinjin** [comment]
@bradkendall I have introduced three endpoints for connectivity.

## Endpoints

### GET `/api/conn/all_statuses`
Used to map "connection code" to it's associated name and description.

Sample output:
```json
[
    {
        "code": 0,
        "name": "CONNECTED",
        "description": "Connection is established."
    },
    {
        "code": 1,
        "name": "DISCONNECTED",
        "description": "Connection is not established."
    },
    {
        "code": 2,
        "name": "CONNECTING",
        "description": "Attempting to connect."
    },
    {
        "code": 3,
        "name": "UNKNOWN",
        "description": "Unable to determine connection status."
    }
]
```

### GET `/api/conn/status`
Obtains the current connectivity status. Only the connectivity code will be returned.

Sample output:
```json
1
```

### GET `/api/conn/reconnect`
Sends a request to reconnect to the network manually.

Sample output:
```json
true
```

## Implementation
- Keep output of `/api/conn/all_statuses` in cache.
- Call `/api/conn/status` in set intervals to stay up to date. 
- When status is `DISCONNECTED`:
    - Manually connect in a set interval (display this to user like: "reconnecting in 30s...").
    - Have button to reconnect manually.
