### ISSUE TITLE
Import cycle error?

### ISSUE THREAD

**Issue by 128-95** [kittycash/wallet#88]
https://github.com/kittycash/wallet/blob/b8f202e056db22b4870aa466638594a5bbe39e6b/src/iko/chain_test.go#L13

with

https://github.com/kittycash/wallet/blob/b8f202e056db22b4870aa466638594a5bbe39e6b/src/cxo/cxo.go#L16

**Comment by 128-95** [comment]
invalid invalid

**Comment by briancaine** [comment]
Per PR #95, this test got commented out.

Just noting it so if the test it important or useful, we can uncomment it later.
