### ISSUE TITLE
wallet-ui

### ISSUE THREAD

**Issue by 128-95** [kittycash/wallet#99]
Sequential:
- [x] Implement [wallet UI](https://github.com/kittycash/wallet-ui) 
- [x] Review design and functionality
- [x] Create release 0.0.0
- [x] Test update notification with creating release 0.0.1
- [x] Add downloadable wallet to website

**Comment by bradkendall** [comment]
I integrated the scoreboard and kitty game (up-kitty) into the play tab.  Are we still disabling it?

Also, this will depend on issue #74

**Comment by 128-95** [comment]
If it's already integrated/ready to go, we can enable it.

We might push signing to a later release.

**Comment by bradkendall** [comment]
@evanlinjin Could you confirm what the actual wallet arguments should be for the release as well.  Here are the current arguments:

`'--test=true',
    '--test-gen-pk=03429869e7e018840dbf5f94369fa6f2ee4b380745a722a84171757a25ac1bb753',
    '--test-root-pk=03429869e7e018840dbf5f94369fa6f2ee4b380745a722a84171757a25ac1bb753',
    '--test-root-nonce=1234',
    '--cxo-address=127.0.0.1:6140',
    '--http-address=127.0.0.1:6148',
    '--messenger-addresses=:8880',
    '--cxo-dir=' + cxo_dir,
    '--gui=true',
    '--gui-dir=' + gui_dir`

**Comment by 128-95** [comment]
If we add a release to Github, the builds we have now will pick that up and show us the notification, right?

I'm thinking of sliming the steps described above down to:
- [ ] Review design and functionality
- [ ] Create release 0.0.1 (marked as *pre-release*)
- [ ] Test update notification on local builds
- [ ] Add downloadable wallet to website

**Comment by jdknives** [comment]
@bradkendall this is done right?

**Comment by evanlinjin** [comment]
Is this done?
